# Site settings
title: Fevelex
description: > # this means to ignore newlines until "baseurl:"

baseurl: "pinkat.github.io" # the subpath of your site, e.g. /blog/
url: "pinkat.github.io" # the base hostname & protocol for your site

# User setting
owner: Fevelex
email: soniafevel@fevelex.es
facebook_username: fevelex
twitter_username:
address:
  - line: C/ PUERTO RICO - Nº4
  - line: AREA EMPRESARIAL
  - line: 28220 MAJADAHONDA - MADRID
  # Feel free to add more lines here 
telephone: 633 910 127
copyright: Pinkat

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag